"""initial

Revision ID: b9f41faf00fc
Revises: 
Create Date: 2026-04-19 17:13:42.858647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import uuid
from utils.auth import hash_password

# revision identifiers, used by Alembic.
revision: str = 'b9f41faf00fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    password = hash_password("qwerty123")
    op.bulk_insert(
        sa.table(
            "users",
            sa.column("id", sa.Integer),
            sa.column("email", sa.String),
            sa.column("full_name", sa.String),
            sa.column("hashed_password", sa.String),
            sa.column("role", sa.Enum("USER", "ADMIN", name="userrole")),
        ),
        [
            {
                "id": 1,
                "email": "user@example.com",
                "full_name": "Test User",
                "hashed_password": password,
                "role": "USER",
            },
            {
                "id": 2,
                "email": "admin@example.com",
                "full_name": "Test Admin",
                "hashed_password": password,
                "role": "ADMIN",
            },
        ],
    )

    op.bulk_insert(
        sa.table(
            "accounts",
            sa.column("id", sa.UUID),
            sa.column("user_id", sa.Integer),
            sa.column("balance", sa.Numeric),
        ),
        [
            {
                "id": uuid.uuid4(),
                "user_id": 1,
                "balance": "0.00",
            },
        ],
    )

    op.execute(
        sa.text("SELECT setval('users_id_seq', (SELECT MAX(id) FROM users))")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_table('users')
    op.execute(sa.text("DROP TYPE IF EXISTS userrole"))
    # ### end Alembic commands ###
